# require: rubocop-performance

AllCops:
  TargetRubyVersion: 2.7.0
  SuggestExtensions: false
  Exclude:
    - 'lib/gem_overrides/*.rb'
    - 'lib/deprecated/**/*'

# Commonly used screens these days easily fit more than 80 characters.
Layout/LineLength:
  Max: 120

# Too short methods lead to extraction of single-use methods, which can make
# the code easier to read (by naming things), but can also clutter the class
Metrics/MethodLength:
  Max: 30

Metrics/BlockLength:
  Max: 100

# The guiding principle of classes is SRP, SRP can't be accurately measured by LoC
Metrics/ClassLength:
  Max: 1500

Style/StringLiterals:
  Enabled: false

Style/FloatDivision:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Metrics/ParameterLists:
  Max: 8
  MaxOptionalParameters: 6

Security/Eval:
  Enabled: false

