# frozen_string_literal: true
source 'https://rubygems.org'

gem 'activesupport'
gem 'actionview'
gem 'bigdecimal'
gem 'chronic'
gem 'configatron'
git 'https://github.com/discordrb/discordrb.git' do
  gem 'discordrb'
  gem 'discordrb-webhooks'
end
gem 'mini_magick'
gem 'mysql2'
gem 'feedjira'
gem 'json'
gem 'net'
gem 'optimist'
gem 'pickup'
gem 'public_suffix'
gem 'sequel'
gem 'redcarpet'
gem 'roo'
gem 'roo-xls'
gem 'rspec'
gem 'terrapin'
gem 'to_regexp'
gem 'yard'
gem 'youtube-dl.rb'
