# frozen_string_literal: true

source 'https://rubygems.org'

gem 'actionview'
gem 'activesupport'
gem 'bigdecimal'
gem 'chronic'
gem 'configatron'
gem 'feedjira'
gem 'http'
gem 'http-parser'
gem 'i18n'
gem 'json'
gem 'mini_magick'
gem 'mysql2'
gem 'nekos'
gem 'net'
gem 'optimist'
gem 'pickup'
gem 'public_suffix'
gem 'rainbow'
gem 'redcarpet'
gem 'roo'
gem 'roo-xls'
gem 'rspec'
gem 'rubocop'
gem 'rubocop-rspec'
gem 'rubocop-sequel'
# gem "rubocop-performance"
gem 'sequel'
gem 'terrapin'
gem 'to_regexp'
gem 'yard'
gem 'youtube-dl.rb'

# Latest release of discordrb
gem 'discordrb', github: 'shardlab/discordrb', branch: 'slash_commands' # branch: 'main'
