PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "schema_migrations" ("version" varchar NOT NULL PRIMARY KEY);
INSERT INTO schema_migrations VALUES('20200523193727');
INSERT INTO schema_migrations VALUES('20210412140707');
INSERT INTO schema_migrations VALUES('20210412172708');
INSERT INTO schema_migrations VALUES('20210925125006');
CREATE TABLE IF NOT EXISTS "ar_internal_metadata" ("key" varchar NOT NULL PRIMARY KEY, "value" varchar, "created_at" datetime(6) NOT NULL, "updated_at" datetime(6) NOT NULL);
INSERT INTO ar_internal_metadata VALUES('environment','development','2021-09-25 13:11:27.001141','2021-09-25 13:11:27.001141');
CREATE TABLE IF NOT EXISTS "users" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "name" varchar NOT NULL, "discriminator" integer, "avatar" varchar, "locale" varchar, "permissions" integer, "created_at" datetime(6) NOT NULL, "updated_at" datetime(6) NOT NULL);
CREATE TABLE IF NOT EXISTS "authorizations" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "provider" varchar NOT NULL, "uid" bigint NOT NULL, "user_id" bigint NOT NULL, "created_at" datetime(6) NOT NULL, "updated_at" datetime(6) NOT NULL);
CREATE TABLE IF NOT EXISTS "reminders" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "datetime" datetime NOT NULL, "message" text, "user_id" bigint NOT NULL, "channel_id" bigint, "repeat" bigint DEFAULT 0, "parent" bigint, "created_at" datetime(6) NOT NULL, "updated_at" datetime(6) NOT NULL);
CREATE TABLE IF NOT EXISTS "highlights" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "content" text, "attachments" text, "author_id" bigint NOT NULL, "timestamp" datetime NOT NULL, "msg_id" bigint NOT NULL, "channel_id" bigint NOT NULL, "server_id" bigint NOT NULL, "highlight_msg_id" bigint NOT NULL, "deleted" boolean NOT NULL, "created_at" datetime(6) NOT NULL, "updated_at" datetime(6) NOT NULL);
CREATE TABLE IF NOT EXISTS "linkeds" ("id" integer NOT NULL PRIMARY KEY, "category" text DEFAULT NULL, "url" text DEFAULT NULL, "timestamp" datetime DEFAULT NULL, "file_hash" text DEFAULT NULL, "author_id" integer DEFAULT NULL, "server_id" integer DEFAULT NULL, "channel_id" integer DEFAULT NULL, "msg_id" integer DEFAULT NULL, "created_at" datetime(6) NOT NULL, "updated_at" datetime(6) NOT NULL);
CREATE TABLE IF NOT EXISTS "triggers" ("id" integer NOT NULL PRIMARY KEY, "phrase" text NOT NULL, "reply" text DEFAULT NULL, "file" text DEFAULT NULL, "user_id" integer NOT NULL, "server_id" integer NOT NULL, "chance" integer DEFAULT 0, "mode" integer DEFAULT 0, "occurrences" integer DEFAULT 0 NOT NULL, "calls" integer DEFAULT 0 NOT NULL, "last_triggered" datetime DEFAULT NULL, "created_at" datetime(6) NOT NULL, "updated_at" datetime(6) NOT NULL);
DELETE FROM sqlite_sequence;
CREATE INDEX "index_users_on_name" ON "users" ("name");
CREATE INDEX "index_authorizations_on_uid" ON "authorizations" ("uid");
CREATE INDEX "index_authorizations_on_user_id" ON "authorizations" ("user_id");
COMMIT;
