# Fill these:
production:
  # Domain where the site exists. For example: rin.domain.com. Remember to set this in Discord API too as Redirect:
  # https://discord.com/developers/applications/APPLICATION_ID/oauth2/general
  web_host: ''
  # Owner Discord ID
  owner_id: ''
  # TohsakaBot's root folder. For example: '/home/rin/TohsakaBot/data'. Default: '../data'
  data_dir: '../data'
  # SSL / HTTPS
  ssl: 'true'
# For developers:
development:
  # Domain where the site exists. For example: rin.domain.com
  web_host: 'localhost:3333'
  # Owner Discord ID
  owner_id: ''
  # TohsakaBot's root folder. For example: '/home/rin/TohsakaBot/data'. Default: '../data'
  data_dir: '../data'
  # SSL / HTTPS
  ssl: 'false'
