# Domain where the site exists. For example: rin.domain.com
web_host: ''
# Owner Discord ID
owner_id: ''
# TohsakaBot's root folder. For example: '/home/rin/TohsakaBot/data'. Default: '../data'
# data_dir: '../data'
