# frozen_string_literal: true

source 'https://rubygems.org'

gem 'bigdecimal', "~>3.1.4"

# Helper functions from Rails
gem 'actionview', "~>7.0.7.2"
gem 'activesupport', "~>7.0.7.2"
gem 'tzinfo-data'

# Config management
gem 'configatron', "~>4.5.1"

# HTTP parsing
gem 'feedjira', "~>3.2.2"
gem 'http', "~>5.1.1"
gem 'http-parser', "~>1.2.3"
gem 'nekos', "~>1.0.1"
gem 'public_suffix', "~>5.0.1"

# Translations
gem 'i18n', "~>1.13.0"

# File parsing
## JSON parsing
gem 'json', "~>2.6.3"
## Markdown parsing
gem 'redcarpet', "~>3.6.0"
## Spreadsheet parsing
gem 'roo', "~>2.10.0"
gem 'roo-xls', "~>1.2.0"

# Database
gem 'mysql2', "~>0.5.5", group: :mysql
gem 'sequel', "~>5.68.0"
gem 'sqlite3', "~>1.6.2", group: :sqlite

# Command parsing
gem 'optimist', "~>3.0.1"

# Probabilities
gem 'pickup', "~>0.0.11"

# Image fingerprinting and similarity
gem 'dhash-vips'

# Command line colors
gem 'rainbow', "~>3.1.1"

gem 'dotenv', '~>2.8.1'

# Development, testing and style checks
group :development do
  gem 'memory_profiler', '~>1.0.0'
  gem 'rspec', '~>3.10.0'
  gem 'rubocop', '~>1.21.0'
  gem 'rubocop-performance', '~>1.11.5'
  gem 'rubocop-rspec', '~>2.5.0'
  gem 'rubocop-sequel', '~>0.3.3'
  gem 'yard', '~>0.9.26'
end

# Latest release of chronic (natural time parsing)
gem 'chronic', github: 'mojombo/chronic', branch: 'master'
# gem 'chronic', "~>0.10.2"

# Latest release of discordrb
gem 'discordrb', github: 'shardlab/discordrb', branch: 'main'
